### ISSUE TITLE
Erase brush Feature in the Drawing Mode

### ISSUE THREAD

**Issue by khushbooag4** [Muhammed-Rahif/Notepad#101] opened 2022-01-10 05:16 UTC
We haven't added Erase Mode in the Drawing Mode.
Can I work on this issue??

**Comment by Muhammed-Rahif** [comment] 2022-01-10 08:29
**We do have these options for erasing drawings(only on draw mode) :-**
- Edit -> Undo. ( <kbd>ctrl</kbd> + <kbd>z</kbd> )
For undo last made change.
- Edit -> Clear. ( <kbd>ctrl</kbd> + <kbd>y</kbd> )
For clear all drawings, but this can also undo which means this doesn't clearing the history of changes.
- Edit -> Erase all. ( no shortcuts )
For erasing all drawings and history of changes. Can't be undo if did it once.
---
But we do not currently have a eraser brush. @khushbooag4 did you mean erase brush or these above features?!

**Comment by khushbooag4** [comment] 2022-01-10 13:25
I am talking about a erase brush

**Comment by Muhammed-Rahif** [comment] 2022-01-10 13:29
@khushbooag4 May I assign this issue to you?

**Comment by Aswin40** [comment] 2022-01-16 15:34
Hi @Muhammed-Rahif 

I was just starting to try out the features of this project. One of the possible workarounds that came into my mind while I was trying out this issue was limiting the background colour to white only then we could possibly use the brush tool with white colour as eraser.

**Comment by Muhammed-Rahif** [comment] 2023-02-23 17:56
Hi @khushbooag4,

I'm writing to let you know that due to unforeseen circumstances, this project has been inactive for the past few months. We apologize for any inconvenience this may have caused.

We've recently switched the technology stack of this project from ReactJS to NextJS. As a result, the issues related to the old stack are no longer applicable.

#### We've deployed the new version of the app to production, and you can access it at this link: **[https://notepad-dusky.vercel.app/](https://notepad-dusky.vercel.app/)**

I would like to take this opportunity to encourage you to actively contribute to the project. If you have any ideas, feature requests, or bug reports, please don't hesitate to create a new issue or submit a pull request on our [GitHub repository](https://github.com/Muhammed-Rahif/Notepad).

Therefore, I'm closing this issue. If you believe that the issue is still relevant to the current version of the project, please feel free to create a new issue and provide details on how to reproduce the problem.

Thank you, @khushbooag4, for your understanding and for your interest in this project! Let's work together to bring it back to life.

Best regards,  
Muhammed Rahif

**Closed by Muhammed-Rahif** 2023-02-23 17:56 UTC
Labels: enhancement, help wanted, priority: high
